name: benela-ai

services:
  - name: backend
    source_dir: /backend
    dockerfile_path: backend/Dockerfile
    http_port: 8000
    instance_size_slug: basic-xxs
    instance_count: 1
    routes:
      - path: /api
    envs:
      - key: APP_ENV
        value: production
      - key: GEMINI_API_KEY
        scope: RUN_TIME
        type: SECRET

  - name: frontend
    source_dir: /frontend
    dockerfile_path: frontend/Dockerfile
    http_port: 3000
    instance_size_slug: basic-xxs
    instance_count: 1
    routes:
      - path: /
    envs:
      - key: NEXT_PUBLIC_API_URL
        value: https://api.benela.dev

domains:
  - domain: benela.dev
    type: PRIMARY
  - domain: www.benela.dev
    type: ALIAS